name: PR Checks

# We don't run these jobs on pull requests because:
# 1. it is often useful to run tests on one's branch without creating a pull
#    request, and
# 2. running on both pushes and pull requests results in the classic problem of
#    having double jobs.
on: push

# Left to-do:
# - coverage
# - publishing docs to gh-pages
# - persistent artifact cache
# - overnight jobs
# - other one-off jobs like missing-deps, plugin jobs etc
# - wsl tasks (TODO: Check if GitHub's Windows runners allow WSL)
#
# New opportunities:
# - run tests on mac (GitHub provides MacOS runners)
# - standardize WSL tasks by using GitHub-provided runners
#
#
# NOTE:
#
# * GitHub Actions do not support YAML variables and/or YAML anchors, which
#   leads to some repetition. Job matrices solve this to some extent but
#   combined with some other issues, this seems like a ongoing source of
#   misery.
# * Not being able to use the standard `container` directive for running our
#   tests is one such example that makes this situation seem worse.
#
# * We have caches etc in GitHub Actions as well, so I don't think we are
#   missing any killer feature.
#
# * Fixing most of the to-do items is mostly mostly a matter of adding more
#   configuration.
# * Some of these tasks can probably live in a different yaml file as a
#   separate workflow.
#
# * Similar to GitLab, GitHub also has a container registry, so we can move our
#   testsuite images there if/when we want to fully migrate off of GitLab.

jobs:
  wsl:
    runs-on: windows-latest
    env:
      WSL_UBUNTU: https://aka.ms/wslubuntu2004
      UBUNTU_EXE: ubuntu2004.exe
    strategy:
      fail-fast: false
      matrix:
        test_suites:
          - sourcecache
          - sources
          - _sourcetests
    steps:
      - name: Install ubuntu for wsl
        shell: powershell
        run: |
          $output = ".\Ubuntu.zip"
          (New-Object System.Net.WebClient).DownloadFile($env:WSL_UBUNTU, $output)
          Expand-Archive .\Ubuntu.zip C:\Windows\Ubuntu
          Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
          C:\Windows\Ubuntu\ubuntu2004.exe install --root
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run exclude script
        shell: powershell
        run: |
          .\exclude-wsl.ps1
      - name: Get necessary packages
        shell: powershell
        run: | 
          wsl -u root -d Ubuntu-20.04 -- /bin/bash -c "apt-get update && apt-get install -y build-essential python3-dev tox"
      - name: Get buildbox
        shell: powershell
        run: | 
          wsl -u root -d Ubuntu-20.04 -- /bin/bash -c "wget https://buildbox-casd-binaries.nyc3.cdn.digitaloceanspaces.com/buildbox-x86_64-linux-0.0.14-872f221d.tar.xz && tar -C /usr/bin -xf buildbox-x86_64-linux-0.0.14-872f221d.tar.xz"
      - name: Test wsl
        shell: powershell
        run: |
          wsl -u root -d Ubuntu-20.04 -- /bin/bash -c "tox -- --color=yes -k ${{ matrix.test_suites }}"
